### ISSUE TITLE
[Edge case] When NIC deletion fails machine stays `CrashLoopBackoff` until `CreationTimeout` without trying re-create

### ISSUE THREAD

**Issue by elankath** [gardener/machine-controller-manager-provider-azure#88]
**What happened**:

The creation of VM, Disk and NIC is done by mcm-provider-azure in [createVMNicDisk](https://github.com/gardener/machine-controller-manager-provider-azure/blob/827c184661b7d99962ad28f75e1de5d7c5ac2ec3/pkg/azure/utils.go#L312). This method is called in [CreateMachine](https://github.com/gardener/machine-controller-manager-provider-azure/blob/40983209c4aa5dbd6d814d0055986e87e7a1f5ee/pkg/azure/core.go#L83) method which is called by the MachineController's [triggerCreationFlow](https://github.com/gardener/machine-controller-manager/blob/5e9582eeb2e09a3648f1b7bf1e63c30fc8a5e5b1/pkg/util/provider/machinecontroller/machine.go#L356). If there is any error in the creation of VM, NIC or disk, then all the three are removed and will be recreated in the subsequent reconciliation.

However, we have an edge case when NIC deletion fails. In that case, the MC changes the machine phase to `CrashLoopBackOff`. In the next reconcile cycle: the `triggerCreationFlow` invokes [Driver.GetMachineStatus](https://github.com/gardener/machine-controller-manager-provider-azure/blob/v0.10.0/pkg/azure/core.go#L180) to get the VM status. Unfortunately, the azure driver impl of this method populates the node name in the response [GetMachineStatusResponse](https://github.com/gardener/machine-controller-manager/blob/v0.48.1/pkg/util/provider/driver/driver.go#L101) if there is a NIC still existing for the VM even if the VM doesn't exist.  This cases the `triggerCreationFlow` to think that the  VM associated with the Machine is already created and populate the `node` label on the machine object with the value in the driver response and skip the machine creation. The machine is then permanently stuck in `CrashLoopBackoff`

**RECENT UPDATES IN BEHAVIOUR**
   1.  In the recent [Azure SDK upgrade PR](https://github.com/gardener/machine-controller-manager-provider-azure/pull/105). `CreateMachine` implementation no longer deletes NIC in case the VM creation failed. It will still return an error but will no delete created NIC.

   
**What you expected to happen**:
1. The [Driver.GetMachineStatus](https://github.com/gardener/machine-controller-manager-provider-azure/blob/v0.10.0/pkg/azure/core.go#L180) should not return the node name for a non-existent VM in the  [GetMachineStatusResponse](https://github.com/gardener/machine-controller-manager/blob/v0.48.1/pkg/util/provider/driver/driver.go#L101).

1. The current [driver.GetMachineStatusResponse](https://pkg.go.dev/github.com/gardener/machine-controller-manager@v0.48.2/pkg/util/provider/driver#GetMachineStatusResponse) only has a `ProviderID` (VM id at cloud provider) and a `NodeName`
This should be enhanced to also contain a `DiskNames`and `NicNames` slice. In other words, the new `driver.GetMachineStatusResponse` should look like the below 
  ```go
  type GetMachineStatusResponse struct {
	ProviderID  string
	NodeName    string
	DiskNames   []string
	NicNames    []string
  }
  ```
   -  If there are utterly no resources found (no vm, disks or nics), then `Driver.GetMachineStatus()` should return a `nil` response and a `status.Error` with `codes.NotFound`. 
   - If there is even a single resource found, then `Driver.GetMachineStatus` should return a populated `GetMachineStatusResponse` struct with a `nil` error. If the VM is present then `ProviderID` is populated, else it is empty.
   - We will need to check this in other provider implementations too and create relevant issues.
3.  The `triggerCreationFlow` currently just checks whether there is an error returned by `Driver.GetMachineStatus()` in order to determine whether to invoke a call to `Driver.CreateMachine`. It should should additionally check if the  check whether `GetMachineStatusResponse.ProviderID` is empty.  
4. The `controller.getVMStatus` helper method invoked in the `triggerDeletionFlow` currently makes a call to `Driver.GetMachineStatus` and ignores the response and only checks the error code. It must now capture and check the response.
    1.  If there is a populated `ProviderID` it should change the operation stage to `InitiateDrain`.  
    1.  if `ProviderID` is empty, but some other resource is found in the response, it should change the operation stage to `InitiateVMDeletion`

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

**Environment**:

**Comment by elankath** [comment]
Created https://github.com/gardener/machine-controller-manager-provider-azure/issues/88

**Comment by himanshu-kun** [comment]
## Post grooming discussion

Because of dealing with NIC separately , when we face problem in deleting them then issue like this can happen

This has happened because of two reasons:
- problem in our driver response design
  - our driver response not sending separate resources (nic, disks, vm) , so presence of even one is considered presence of all and we don't retry creation for `CrashLoopbackoff` machines
  
- Azure API sending unexpected responses
  - ideally Azure API should allow deletion of NIC , but in this case its not
  - this can be solved by updating azure-go-sdk , because then we don't have deal with NICs separately and only azure deals with them(cascade delete) and this way presence of 1 resource can be safely considered presence of all.

**Comment by unmarshall** [comment]
We can leverage resource-graph API to get this cheaply.
```
resources
| extend tagKeys = bag_keys(tags)
| where tagKeys hasprefix "kubernetes.io-cluster-" and tagKeys hasprefix "kubernetes.io-role-"
| where name startswith "<vm-name>"
| project name, type
```
In a single query you can get all resources created and associated to a VM.

The above query leverages the existing convention that we have for all resources created:
- NIC has a name: "<vm-name>-nic"
- OSDisk has a name: "<vm-name>-os-disk"
- DataDisk has a name: "<vm-name>-data-disk"

**Comment by himanshu-kun** [comment]
The above issue doesn't occur anymore. It has solved by the following :
1) `GetMachineStatus()` has been updated to be in sync with the contract and return `NotFound` error only if VM is not found. Means if the nics, disks are there , and VM not there, then also it'll return `NotFound`. This allows for re-create operation being tried in every reconcile

Further `CreateMachine()` has been impoved to not delete NIC if VM creation fails, so that in the next reconcile VM creation is retried directly. This allows to avoid errors due to NIC deletion

But there still is a scope of orphan resources being left even after machine deletion. This is due to the updated behavior of `GetMachineStatus()` and how its used in deletion flow.

Will open another issue to deal with that corner case.

/close
